"$schema" = 'https://starship.rs/config-schema.json'

# 設置單行提示格式，包含作業系統、使用者名稱、主機名稱、目錄和 Git 狀態
# format = "$os[$username](yellow)[@](cyan)[$hostname](green)[$directory](purple)[$git_branch$git_status](dimmed white)$character"
format = """
[░▒▓](green)\
$os\
[$username](yellow)\
[ ](green)\
[$directory](purple)\
[$git_branch$git_status]\
(dimmed white)$character\
"""

# 使用者名稱，始終顯示
[username]
show_always = true
style_user = "#696987"
style_root = "red"
format = "[$user]($style bg:green)"
disable = false

# 字符設置，成功和失敗符號
[character]
success_symbol = "[➜](bold green)"
error_symbol = "[➜](bold red)"

# 作業系統符號
[os]
disabled = false
style = "bold black bg:green"

[os.symbols]
Alpine = " "
Amazon = " "
Android = " "
Arch = " "
CentOS = " "
Debian = " "
DragonFly = " "
Emscripten = " "
EndeavourOS = " "
Fedora = " "
FreeBSD = " "
Garuda = "﯑ "
Gentoo = " "
HardenedBSD = "ﲊ "
Illumos = " "
Linux = " "
Macos = " "
Manjaro = " "
Mariner = " "
MidnightBSD = " "
Mint = " "
NetBSD = " "
NixOS = " "
OpenBSD = " "
openSUSE = " "
OracleLinux = " "
Pop = " "
Raspbian = " "
Redhat = " "
RedHatEnterprise = " "
Redox = " "
Solus = " "
SUSE = " "
Ubuntu = " "
Unknown = " "
Windows = " "

# 主機名稱，始終顯示
[hostname]
ssh_only = false
style = "green"
format = "[$hostname]($style)"

# 目錄設置，簡化顯示
[directory]
style = "purple"
truncation_length = 3
truncate_to_repo = true
read_only = " "
read_only_style = "red"

# Git 分支和狀態，僅在 Git 儲存庫中顯示
[git_branch]
symbol = " "
style = "dimmed white"
format = "[$symbol$branch]($style)"

[git_status]
style = "dimmed white"
format = "([$all_status$ahead_behind]($style))"

# 禁用不必要的模組以保持簡潔
[battery]
disabled = true

[time]
disabled = true

[c]
disabled = true

[cpp]
disabled = true

[rust]
disabled = false

[java]
disabled = true

[golang]
disabled = false

[nodejs]
disabled = true

[python]
disabled = true

[docker_context]
disabled = false

[kubernetes]
disabled = true
