local wezterm = require('wezterm')
local mux = wezterm.mux

local SOLID_LEFT_ARROW = wezterm.nerdfonts.ple_lower_right_triangle
local SOLID_RIGHT_ARROW = wezterm.nerdfonts.ple_upper_left_triangle

-- log level
wezterm.log_level = 'debug'

wezterm.on("format-tab-title", function(tab, tabs, panes, config, hover, max_width)
  local background = '#5c6d74'
  local foreground = '#FFFFFF'
  local edge_background = 'none'
  if tab.is_active then
    background = '#5151A2'
    foreground = '#FFFFFF'
  end
  local edge_foreground = background
  local title = "  " .. wezterm.truncate_right(tab.active_pane.title, max_width -1) .. "  "
  return {
    { Background = { Color = edge_background } },
    { Foreground = { Color = edge_foreground } },
    { Text = SOLID_LEFT_ARROW },
    { Background = { Color = background } },
    { Foreground = { Color = foreground } },
    { Text = title },
    { Background = { Color = edge_background } },
    { Foreground = { Color = edge_foreground } },
    { Text = SOLID_RIGHT_ARROW },
  }
end)

return {
  -- ================
  -- Basic Set
  -- ================
  automatically_reload_config = true,

  -- ================
  -- 外觀設定
  -- ================

  -- 主題顏色 "Catppuccin Macchiato"
  -- color_scheme = 'Dracula',
  color_scheme = 'Tokyo Night',

  -- 模糊效果


  -- 隱藏視窗標題列
  window_decorations = "RESIZE", -- "NONE", "RESIZE"


  -- ================
  -- 分頁與視窗管理
  -- ================

  -- 背景圖片
  -- background = {
  -- --   {
  -- --     source = {
  -- -- --       圖片路徑(建議使用絕對路徑)
  -- --       File = 'D:\\Felix\\img\\nightCatAndRain.jpg',
  -- --     },
  -- -- --     圖片縮放模式
  -- --     resize = "NoScale",

  -- -- --     圖片背景透明度
  -- --     opacity = 0.4,
  -- --   },
  -- -- Terminal 背景顏色, 可以跟圖片一起混搭
  --   {
  --     source = { Color = 'rgba(30,30,30,0.7)'},
  --     height = '100%',
  --     width = '100%',
  --   }
  -- },

  -- 窗口設置
  window_background_opacity = 0.65, -- 透明度
  -- macos_window_background_blur = 100, -- 模糊效果(macOS system)
  -- win32_system_backdrop = 'Acrylic', -- Windows 專屬

  -- 分頁欄放置在底部
  tab_bar_at_bottom = true,
  colors = {
    -- selection_bg = '#FFFFFF', -- Select block background color
    -- selection_fg = '#FFFFFF', -- Select block font color
    tab_bar = {
      active_tab = {
        bg_color = '#2E2E2E',
        fg_color = '#FFFFFF',
      },
      inactive_tab = {
        bg_color = '#1E1E1E',
        fg_color = '#B0B0B0',
      },
    },
  },

  -- 增強型分頁(支援圖標)
  use_fancy_tab_bar = true,
  -- 隱藏分頁欄位, 除非有多個分頁
  enable_tab_bar = true,
  -- 單一分頁時隱藏分頁欄位
  hide_tab_bar_if_only_one_tab = true,

  -- tab_bar opacity
  window_frame = {
    inactive_titlebar_bg = "none",
    active_titlebar_bg = 'none',
  },
  --這是什麼我不知道,但挺漂亮的
  window_background_gradient = {
    colors = { "#000000" },
  },
  -- 隱藏 tab_bar 建立新分頁按鈕
  show_new_tab_button_in_tab_bar = false,
  -- Nightly Builds Only
  -- 隱藏 tab_option 關閉按鈕
  -- show_close_tab_button_in_tabs = false,

  -- ================
  -- SSH 連線設定
  -- ================

  -- 透過 LEADER + s 開啟 launch_menu
  launch_menu = {
    {
      label = 'SSH felix_199',
    args = { 'ssh', 'fanice@felix_199'},
    },
  },



  -- ================
  -- 視窗分割
  -- ================
  keys = {
    -- 視窗分割
    { key = '\\', mods = 'LEADER', action = wezterm.action.SplitVertical { domain = 'CurrentPaneDomain' } },
    { key = '-', mods = 'LEADER', action = wezterm.action.SplitHorizontal { domain = 'CurrentPaneDomain' } },

    -- 退出當前視窗分割
    -- 按下 LEADER 後再按 q
    { key = 'q', mods = 'LEADER', action = wezterm.action.CloseCurrentPane { confirm = true } },

    -- 在分割視窗中移動焦點
    -- Vim 風格
    { key = 'h', mods = 'LEADER', action = wezterm.action.ActivatePaneDirection('Left') },
    { key = 'l', mods = 'LEADER', action = wezterm.action.ActivatePaneDirection('Right') },
    { key = 'k', mods = 'LEADER', action = wezterm.action.ActivatePaneDirection('Up') },
    { key = 'j', mods = 'LEADER', action = wezterm.action.ActivatePaneDirection('Down') },

    -- 分頁切換
    { key = 'Tab', mods = 'CTRL', action = wezterm.action.ActivateTabRelative(1) },
    { key = 'Tab', mods = 'CTRL|SHIFT', action = wezterm.action.ActivateTabRelative(-1) },

    -- 關閉分頁
    { key = 'w', mods = 'LEADER', action = wezterm.action.CloseCurrentTab { confirm = true } },

    -- 建立新分頁
    { key = 't', mods = 'LEADER', action = wezterm.action.SpawnTab('CurrentPaneDomain') },

    -- 開啟 launch_menu
    -- LEADER + s
    { key = 's', mods = 'LEADER', action = wezterm.action.ShowLauncher },

    -- 重新載入設定檔，方便調整
    { key = 'r', mods = 'LEADER', action = wezterm.action.ReloadConfiguration },

    -- 常用快捷鍵設定
    -- 複製
    -- { key = 'c', mods = 'LEADER', action = wezterm.action.CopyTo 'Clipboard' },
    -- 貼上
    -- { key = 'v', mods = 'LEADER', action = wezterm.action.PasteFrom 'Clipboard' },
  },

  -- 設定 LEADER 鍵為 CTRL+a，方便與 GNU Screen 或 tmux 相容
  leader = { key = 'a', mods = 'CTRL'},

  -- 啟動時自動最大化視窗
  -- enable_kitty_graphics = true,

  -- 啟用滑鼠滾動
  -- enable_scroll_bar = true,

  -- =======================================================================================
  -- 其他進階設定
  -- =======================================================================================

  -- 啟動時執行的指令
  -- 可以設定啟動時自動切換到特定的 shell
  -- Windows system
  default_prog = { 'C:\\Users\\felixhuang\\scoop\\apps\\msys2\\current\\usr\\bin\\fish.exe'},
  -- Mac system or Linux system
  -- default_prog = { '/opt/homebrew/bin/fish' },

  -- 跨平台鍵盤設置
  use_ime = true, -- 啟用輸入法支援(適合中文輸入)


  -- 視窗邊界調整
  -- window_padding = {
  --   left = 0,
  --   right = 0,
  --   top = 0,
  --   bottom = 0,
  -- },
}
